sut:
  build: .
  dockerfile: Dockerfile.test
  links:
    - web
    
redis:
  image: redis
db:
  image: postgres

web:
  build: .
  dockerfile: Dockerfile
  volumes:
    - .:/myapp
  links:
    - redis
    - db