development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:

test:
  <<: *default
  database: red_green_test

production:
  <<: *default
  database: red_green_production
